local ink = require "ink.story" 

function init(self)

	local res = sys.load_resource("/assets/Untitled.json")
	local story = ink.create(res)

	repeat
		pprint("======================")
		local paragraphs, answers = story.continue(1)
		for _, p in ipairs (paragraphs) do
			pprint(p.text)
		end

		if #answers > 0 then
			pprint("----------------------")
			for i, a in ipairs (answers) do
				pprint("[" .. i .. "] " .. a)
			end
		end
	until #answers == 0 

	pprint("- T H E - E N D -")
	
end
